export const totalDuration = 420;

export const slides = [
  {
    id: "cover",
    layout: "cover",
    eyebrow: "Climate Intelligence in Motion",
    title: "GreenWings AI",
    subtitle: "Aviation Environmental Footprint Advisor",
    section: "Opening",
    start: 0,
    end: 20,
    color: "#2dd4bf",
    statement: "From carbon reporting to climate-aware decisions",
    notes: "Open as an aviation-technology product, not a sustainability school project. Establish the shift from reporting to decisions.",
  },
  {
    id: "problem",
    layout: "problem",
    eyebrow: "Problem",
    title: "The Problem",
    section: "Problem",
    start: 20,
    end: 50,
    color: "#38bdf8",
    statement: "Aviation is hard to decarbonise.",
    fragments: ["CO2 reporting", "Fuel efficiency", "Contrail-risk signals", "SAF planning"],
    gap: "Teams still lack a clear answer: what should we do next?",
    notes: "Frame the gap: teams have data and tools, but not an integrated decision layer.",
  },
  {
    id: "insight",
    layout: "impactStack",
    eyebrow: "Insight",
    title: "It is not just CO2",
    section: "Insight",
    start: 50,
    end: 80,
    color: "#38bdf8",
    statement: "Climate impact is broader than fuel burn alone.",
    layers: [
      { label: "Contrail cirrus", value: 57.4, tone: "sky" },
      { label: "CO2", value: 34.3, tone: "teal" },
      { label: "NOx", value: 17.5, tone: "amber" },
      { label: "Water vapour", value: 4.5, tone: "muted" },
      { label: "Soot", value: 2.2, tone: "muted" },
    ],
    callout: "Uncertainty matters",
    notes: "Make contrail cirrus visually dominant while acknowledging uncertainty. Do not overstate precision.",
  },
  {
    id: "industry-gap",
    layout: "journey",
    eyebrow: "Industry Gap",
    title: "The missing layer is decision support",
    section: "Market Gap",
    start: 80,
    end: 110,
    color: "#38bdf8",
    stages: [
      { label: "Reporting", capability: "Carbon reporting tools", status: "covered" },
      { label: "Forecasting", capability: "Contrail forecasting trials", status: "covered" },
      { label: "Optimisation", capability: "Fuel optimisation platforms", status: "covered" },
      { label: "Decision", capability: "Climate, cost, feasibility, operations", status: "gap" },
    ],
    question: "What action delivers the best climate, cost, feasibility, and operational outcome?",
    notes: "Position GreenWings after existing tools. The opportunity is not another calculator; it is the decision layer.",
  },
  {
    id: "solution",
    layout: "orchestrator",
    eyebrow: "Our Solution",
    title: "GreenWings Decision Copilot",
    section: "Solution",
    start: 110,
    end: 140,
    color: "#2dd4bf",
    inputs: ["Dashboard data", "Flight data", "Fuel data", "Emissions models"],
    outputs: ["Ranked recommendations", "Scenario evidence", "Human approval"],
    center: "GreenWings AI Orchestrator",
    notes: "Avoid chatbot framing. This is an orchestrator that coordinates trusted tools and produces decision-ready outputs.",
  },
  {
    id: "workflow",
    layout: "workflow",
    eyebrow: "How It Works",
    title: "From scenario to decision brief",
    section: "Workflow",
    start: 140,
    end: 170,
    color: "#2dd4bf",
    steps: [
      "Select flight, route, or fleet scenario",
      "Analyse fuel, CO2, and emissions data",
      "Identify drivers and quality flags",
      "Test mitigation scenarios",
      "Generate human-approved decision brief",
    ],
    notes: "Describe the product flow as a controlled workflow. Every step is grounded in available data.",
  },
  {
    id: "architecture",
    layout: "architecture",
    eyebrow: "Architecture",
    title: "The AI does not invent numbers",
    section: "Architecture",
    start: 170,
    end: 205,
    color: "#8b5cf6",
    top: ["User", "Web dashboard", "Scenario builder"],
    tools: [
      "Flight and route data",
      "Fuel and CO2 estimator",
      "OpenAP emissions",
      "Mitigation knowledge base",
      "Scenario simulator",
      "Audit-log tool",
    ],
    data: ["Airports", "Flight metadata", "Fuel-labelled flights", "Trajectories", "OpenAP", "Evidence tables"],
    side: "Human review and approval",
    principle: "Tools generate figures. AI orchestrates and explains.",
    notes: "Make governance visible in the architecture. Deterministic tools own numerical outputs.",
  },
  {
    id: "dashboard",
    layout: "metricsDashboard",
    eyebrow: "Data Strength",
    title: "A real operating dataset",
    section: "Dataset",
    start: 205,
    end: 240,
    color: "#38bdf8",
    badge: "Detailed fuel and emissions analytics: rank flights only",
    metrics: [
      { value: "15,761", label: "flights" },
      { value: "1,189", label: "routes" },
      { value: "8,787", label: "airports" },
      { value: "27", label: "aircraft types" },
      { value: "1,888", label: "fuel-labelled flights" },
      { value: "24,289", label: "fuel intervals" },
      { value: "32.27M kg", label: "derived CO2" },
    ],
    notes: "Present the dataset as a strength while clearly scoping the detailed analytics to rank flights.",
  },
  {
    id: "data-challenges",
    layout: "riskControls",
    eyebrow: "Data Challenges",
    title: "Limitations are labelled, not hidden",
    section: "Controls",
    start: 240,
    end: 270,
    color: "#f59e0b",
    risks: [
      "Fuel data only for rank flights",
      "Missing fuel data for train and final groups",
      "10,549 intervals under five minutes",
      "Large trajectory ZIP files",
      "No real-time atmospheric or contrail data",
    ],
    controls: [
      "Data coverage labels",
      "Quality flags",
      "Lazy trajectory loading",
      "Supplied vs modelled separation",
      "Decline unsupported recommendations",
      "Uncertainty-aware output",
    ],
    notes: "Use this slide to build trust. The system makes limitations operationally visible.",
  },
  {
    id: "agentic-workflow",
    layout: "agentWorkflow",
    eyebrow: "Agentic AI Workflow",
    title: "Orchestration with safeguards",
    section: "Agent",
    start: 270,
    end: 300,
    color: "#2dd4bf",
    request: "Reduce the climate impact of this route with minimal disruption.",
    calls: [
      "Validate flight and data coverage",
      "Retrieve fuel and emissions data",
      "Check interval quality",
      "Run scenario options",
      "Rank measures",
      "Generate evidence-backed decision brief",
      "Send to human reviewer",
    ],
    gate: "Safeguard gate",
    notes: "Show the agent as a controlled sequence of tool calls with a review gate before finalization.",
  },
  {
    id: "governance",
    layout: "governance",
    eyebrow: "Trust, Control and Governance",
    title: "AI governance is designed in, not added after deployment",
    section: "Governance",
    start: 300,
    end: 330,
    color: "#8b5cf6",
    controls: [
      { title: "Trust", body: "Source traceability" },
      { title: "Understandability", body: "Explanation and rationale" },
      { title: "Control", body: "Strict tool allowlist" },
      { title: "Human in the loop", body: "Mandatory approval" },
      { title: "Monitoring", body: "Audit logs and feedback" },
      { title: "Accountability", body: "Named decision owner" },
    ],
    notes: "Governance is part of the product experience, not a compliance appendix.",
  },
  {
    id: "decision-brief",
    layout: "decisionBrief",
    eyebrow: "Example Decision Brief",
    title: "Decision-ready, not dashboard-only",
    section: "Product",
    start: 330,
    end: 360,
    color: "#2dd4bf",
    summary: [
      { label: "Baseline", value: "High non-CO2 exposure" },
      { label: "Main driver", value: "Persistent contrail risk" },
    ],
    options: [
      { action: "Altitude adjustment", benefit: "High", cost: "Low", feasibility: "Medium", confidence: "0.72" },
      { action: "Departure window shift", benefit: "Medium", cost: "Low", feasibility: "High", confidence: "0.68" },
      { action: "SAF blend scenario", benefit: "Medium", cost: "High", feasibility: "Medium", confidence: "0.61" },
    ],
    status: "Draft - awaiting qualified review",
    notes: "Make the product tangible. Show recommendation ranking with cost, feasibility, confidence, and review status.",
  },
  {
    id: "positioning",
    layout: "positioning",
    eyebrow: "Positioning",
    title: "The non-CO2-aware decision-support layer",
    section: "Positioning",
    start: 360,
    end: 385,
    color: "#38bdf8",
    tools: ["Carbon calculators", "Fuel-optimisation platforms", "Contrail forecasts", "Static decarbonisation reports"],
    greenwings: "GreenWings helps teams decide what to do.",
    line: "Existing tools tell teams what happened.",
    notes: "Position around integration and decisions rather than replacing every existing aviation tool.",
  },
  {
    id: "why-now",
    layout: "timeline",
    eyebrow: "Why Now",
    title: "The market is moving toward governed climate decisions",
    section: "Timing",
    start: 385,
    end: 405,
    color: "#f59e0b",
    events: [
      "Rising aviation climate pressure",
      "SAF adoption and compliance requirements",
      "Growing non-CO2 monitoring expectations",
      "Contrail avoidance entering airline trials",
      "Enterprise demand for governed AI",
    ],
    close: "The next aviation advantage is not more reporting. It is better climate decisions.",
    notes: "Create urgency without overclaiming. Regulation, operational trials, and AI governance are converging.",
  },
  {
    id: "closing",
    layout: "closing",
    eyebrow: "Close",
    title: "Measure less. Decide better.",
    section: "Closing",
    start: 405,
    end: 420,
    color: "#22c55e",
    subline: "GreenWings AI helps aviation see, understand, and reduce its environmental footprint with human accountability.",
    notes: "Close with the product promise and the human-accountability point.",
  },
];
